### ISSUE TITLE
These instructions are not consistent with the current repository

### ISSUE THREAD

**Issue by rhyde** [nLabs-nScope/nScope#1]
Attempting to build, I find that the nScope-electron directory is missing.

**Comment by davidjmeyer** [comment]
you should checkout the `develop` branch to get the latest, then the directions should work.

That said, this project is a bit on hold while we work on the backend. Once the backend is to a stable point, we plan to pick this project back up and continue.

**Comment by davidjmeyer** [comment]
Whoops, actually I missed your point. A while back I renamed the repository without updating the README.

fixed now, thanks!
