### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by electricfish** [nLabs-nScope/nScope#19]
When you poke the button, don't clear the trace display, that's good info, just stop it (could give some non-lossy indication that nScope has powered off)

Roll mode, with data logging, converts it into a DAQ platform for many experiments.   I'd rather have fewer dialogs and choices - just poke "log to file", no conversation about filenames etc

XY mode and persistence, less important than roll/DAQ, but still lovely

Trigger should show as lines on X and Y axes, as previous, and have a slider to adjust it on the scope face.  It would be nice if the trace color that trigger relates to were shown on the face, as well.  Maybe the trigger line(s) could be colored as the trace.

"About" should tell us about the connected hardware as well - version and year, and any device diagnostic info or failed features, that is easily available.

User ability to null the input offset.  Students ask for this, but it's not clear it's worth providing another knob to twiddle.

More later.

-Michael

**Comment by davidjmeyer** [comment]
These requests look like they've been filed as individual issues.
