### ISSUE TITLE
Scope trace visibility could use improvement

### ISSUE THREAD

**Issue by michaelpeshkin** [nLabs-nScope/nScope#30]
I'd very much prefer black for the face background.   We have a problems with 4-trace visibility already.  Prioritize thin lines, no interpolated pixels.    Grey not white fiducial lines.   I'd perfer a very clean look, like an instrument not an object.  Max vis.

Similarly, I appreciate the very simple channels and output selectors and their consistency of operation.  

Maybe some words of reassurance: Analog signal generators, scope channels, etc?

**Comment by davidjmeyer** [comment]
Scheduled for next week.
