### ISSUE TITLE
Status line, tuned to novice users

### ISSUE THREAD

**Issue by michaelpeshkin** [nLabs-nScope/nScope#67]
Near the traditional Run/Single/Stop, put a line of text that expalins why the scope is (not) doing something.  It may have to do with power/fault, or trigger type & status, or what mode is selected.

waiting for trigger
single sweep occurred, stopped now
±5 is off due to power button pushed  
±5 is off due to overcurrent fault
no trace selected, choose at least one
XY mode
Roll mode, no logging
Roll mode with logging, 52876 samples so far...

**Comment by davidjmeyer** [comment]
duplicate of #28
