### ISSUE TITLE
Slider inputs need a way for precision input

### ISSUE THREAD

**Issue by huddle7** [nLabs-nScope/nScope#83]
A few points of interest for us.

Please include the trigger.
Prefer right clicking the sliders for precise inputs.
Save a captured signal as a CSV

**Comment by davidjmeyer** [comment]
Trigger work is tracked under issue https://github.com/nLabs-nScope/nScope/issues/68
Signal capture to CSV is tracked under issue https://github.com/nLabs-nScope/nScope/issues/72

Retitling this to track the work for precision slider input.

**Comment by davidjmeyer** [comment]
Working on this, I'm thinking I'll make this a nice in-line editing feature:
<img width="173" alt="image" src="https://github.com/user-attachments/assets/b5584cf1-d2ef-49a2-9c53-62fcf3cab26d">

**Comment by huddle7** [comment]
Looks good, thanks!

Steve


Stephen Huddle

Department of Bioengineering

University of Colorado, Denver

303.921.4280

https://engineering.ucdenver.edu/bioengineering<https://url.avanan.click/v2/___https:/engineering.ucdenver.edu/bioengineering___.YXAzOmdlY286YTpvOjhkMjA1NzMxODM0M2YwODUwODk4NDFjMWM1ZjFhMDc1OjY6NjhhMTo0OGNmZGNjNmI4N2YxMDY4ZTM5Mjk0ODZhMzYwMWI3OWFlMDIzZGIzMWIwMDJhMTQwY2RjNWY3NDU5MDJmOTM4Omg6VA>



________________________________
